### ISSUE TITLE
Just stopped working on Windy

### ISSUE THREAD

**Issue by nrbray** [vicb/windy-plugin-sounding#11]
Dear Victor,

Please may I raise a ticket to track the progress towards getting the plugin "compatible" or otherwise working again in Windy after some recent major change.

aafaics there are two issues based on the statement from @ivo_at_Windy

" If alternative sounding plugin will not appear we can enhance our core sounding to match its functionality" 

and @Sutry_at_Windy

"We wanted to remove the whole plugin system, but there were many requests to keep it in Windy. So we updated the system and it should be now much easier to manage these plugins by their developers. However, we can't still wait for all developers with every update. .... we informed all developers of them 2 months ago about the new implementation."

1. We can help @vicb make the "alternative sounding plugin" appear 
2. &/or We can ask Windy to ""match its functionality

https://community.windy.com/post/186279

https://community.windy.com/post/186337

https://community.windy.com/post/186348

https://community.windy.com/post/186196

Best regards Nigel

**Comment by vicb** [comment]
I'm on it. 

People can help by contributing code, good karma or even money via buymeacoffee.com/vic.b
The later option is very much appreciated. 

Expect something in matter of days.

Thanks
