### ISSUE TITLE
Don't switch to clouds layer when choosing "Better sounding" from right-click menu

### ISSUE THREAD

**Issue by stanleyguevara** [vicb/windy-plugin-sounding#8]
To reproduce:
* Pick wind layer from windy menu
* Close sounding plugin tab (if it was open)
* Right click anywhere, pick "Better sounding"
The windy layer switches automatically to clouds

Is this intentional? Doesn't seem so...

Awesome plugin btw, loving it!

**Comment by vicb** [comment]
Oops, only seeing this now.
This is the intended behavior.

**Comment by stanleyguevara** [comment]
Not sure how overriding user choice is good UX, but oh well.
